name: ReActions
main: me.fromgate.reactions.ReActions
version: 0.0.3/2
website: http://fromgate.me
author: fromgate, fromgate@gmail.com
softdepend: [Vault,Towny,WorldGuard]
commands:
   react:
      aliases: [ra,rea,rct]
      description: 
      usage: 
           /react help