name: ReActions
main: me.fromgate.reactions.ReActions
version: 0.10.0
website: http://fromgate.me
author: fromgate, fromgate@gmail.com
softdepend: [Vault,Towny,WorldGuard,RacesAndClasses,PlayEffect,Factions,Craftconomy3,ProtocolLib,PlaceholderAPI]
commands:
   react:
      aliases: [ra,rea,rct]
      description: Main command of ReActions 
      usage: 
           /react help
   exec:
      aliases: [execute,run]
      description: execute EXEC-activator  
      usage: 
           /exec <ActivatorId> [player:<PlayerSelector>] [delay:<Time>]